# Generated by Django 3.1.7 on 2021-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('preparing', 'preparing'), ('started', 'started'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], max_length=20)),
            ],
        ),
    ]
